# **Tugas 2 : Deskritisasi Data**

Senin, 5 September 2022


**- Definisi:**

Diskritisasi yaitu proses mengubah data bertipe numerik menjadi data bertipe kategorikal.




**- Metode:**

Diskritisasi memiliki 2 pendekatan yaitu *equal-width intervals* dan *equal-frequency intervals*

  *   Equal-width intervals : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar. 
  *   Equal-frequency intervals : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota per kelompok yang kurang lebih sama besar.
      
Diskritisasi dengan basis Entropy

 * Entropy digunakan untuk menentukan yang manakah node yang akan
menjadi pemecah data latih berikutnya

 **Carilah data yang bertipe numerik (data klasifikasi)**

Membaca Data

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
#membaca dataset
url = "https://raw.githubusercontent.com/RibutDwiArtah023/datamining/main/IRIS.csv"
df = pd.read_csv(url)
pd.options.mode.chained_assignment = None
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
#mengetahui info dari dataset yang telah di baca melalui URL
df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
# show first 10 rows
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [5]:
sepal_length = df["sepal_length"]
sepal_width = df["sepal_width"]
petal_length = df["petal_length"]
petal_width = df["petal_width"]

###**Soal 1**
**Lakukan proses diskritisasi dengan equal width dan equal frequency**


**- Equal Width Intervals**

Untuk menghitung equal width, dibutuhkan library pandas dengan menggunakan method "cut". Buat 3 label untuk mengkategorikan batas tiap ukuran petal dan sepal dengan menggunakan small, medium, large.

* Sepal Length

In [7]:
# perhitungan atribut sepal length tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut lebar petal dalam cm (1.4)
interval_sepalLength = pd.cut(df['sepal_length'],amount_of_binning,True).value_counts()
print(interval_sepalLength)

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal_length, dtype: int64

In [9]:
#perhitungan atribut lebar  

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
#melakukan binning dengan atribut lebar petal dalam cm (1.4)
label_sepalLenght = pd.cut(df['sepal_length'],amount_of_binning, True, labels)
sepalLength_binning = label_sepalLenght.value_counts()
print(sepalLength_binning)

medium    71
small     59
large     20
Name: sepal_length, dtype: int64

In [10]:
# menampilkan dataframe sepal_lenght
tb_sepalLength = pd.concat((df["sepal_length"],label_sepalLenght), axis=1)
tb_sepalLength

    sepal_length sepal_length
0            5.1        small
1            4.9        small
2            4.7        small
3            4.6        small
4            5.0        small
..           ...          ...
145          6.7       medium
146          6.3       medium
147          6.5       medium
148          6.2       medium
149          5.9       medium

[150 rows x 2 columns]

* Sepal Width

In [11]:
# perhitungan atribut sepal width tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut lebar petal dalam cm (1.4)
interval_sepalWidth = pd.cut(df['sepal_width'],amount_of_binning,True).value_counts()
print(interval_sepalWidth)

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

In [12]:
# perhitungan atribut sepal width label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
#melakukan binning dengan atribut lebar petal dalam cm (1.4)
label_sepalWidth = pd.cut(df['sepal_width'],amount_of_binning, True, labels)
sepalWidth_binning= label_sepalWidth.value_counts()
print(sepalWidth_binning)

medium    88
small     47
large     15
Name: sepal_width, dtype: int64

In [13]:
# menampilkan dataframe sepal_width
tb_sepalWidth = pd.concat((df["sepal_width"],label_sepalWidth), axis=1)
tb_sepalWidth

    sepal_width sepal_width
0           3.5      medium
1           3.0      medium
2           3.2      medium
3           3.1      medium
4           3.6      medium
..          ...         ...
145         3.0      medium
146         2.5       small
147         3.0      medium
148         3.4      medium
149         3.0      medium

[150 rows x 2 columns]

* Petal Length

In [14]:
# perhitungan atribut petal length tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut lebar petal dalam cm (1.4)
interval_petalLength = pd.cut(df['petal_length'],amount_of_binning,True).value_counts()
print(interval_petalLength)

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal_length, dtype: int64

In [15]:
# perhitungan atribut petal width label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
#melakukan binning dengan atribut lebar petal dalam cm (1.4)
label_petalLength = pd.cut(df['petal_length'],amount_of_binning, True, labels)
l_petal_binning = label_petalLength.value_counts()
print(l_petal_binning)

medium    54
small     50
large     46
Name: petal_length, dtype: int64

In [16]:
# menampilkan dataframe petal_length
tb_petalLength = pd.concat((df["petal_length"],label_petalLength), axis=1)
tb_petalLength

    petal_length petal_length
0            1.4        small
1            1.4        small
2            1.3        small
3            1.5        small
4            1.4        small
..           ...          ...
145          5.2        large
146          5.0        large
147          5.2        large
148          5.4        large
149          5.1        large

[150 rows x 2 columns]

* Petal Width

In [17]:
# perhitungan atribut petal width tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut lebar petal dalam cm (1.4)
interval_petalWidth = pd.cut(df['petal_width'],amount_of_binning,True).value_counts()
print(interval_petalWidth)

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal_width, dtype: int64

In [18]:
# perhitungan atribut petal width label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
#melakukan binning dengan atribut lebar petal dalam cm (1.4)
label_petalWidth = pd.cut(df['petal_width'],amount_of_binning, True, labels)
w_petal_binning = label_petalWidth.value_counts()
print(w_petal_binning)

medium    54
small     50
large     46
Name: petal_width, dtype: int64

In [19]:
# menampilkan dataframe petal_length
tb_petalWidth=pd.concat((df["petal_width"],label_petalWidth), axis=1)
tb_petalWidth

    petal_width petal_width
0           0.2       small
1           0.2       small
2           0.2       small
3           0.2       small
4           0.2       small
..          ...         ...
145         2.3       large
146         1.9       large
147         2.0       large
148         2.3       large
149         1.8       large

[150 rows x 2 columns]

Menampilkan hasil diskritisasi Equal Width

In [20]:
pd.concat((label_sepalLenght,label_sepalWidth,label_petalLength,label_petalWidth,df["species"]), axis=1)

    sepal_length sepal_width petal_length petal_width         species
0          small      medium        small       small     Iris-setosa
1          small      medium        small       small     Iris-setosa
2          small      medium        small       small     Iris-setosa
3          small      medium        small       small     Iris-setosa
4          small      medium        small       small     Iris-setosa
..           ...         ...          ...         ...             ...
145       medium      medium        large       large  Iris-virginica
146       medium       small        large       large  Iris-virginica
147       medium      medium        large       large  Iris-virginica
148       medium      medium        large       large  Iris-virginica
149       medium      medium        large       large  Iris-virginica

[150 rows x 5 columns]

**- Equal Frequency Intervals**

 Untuk menghitung equal frequency, dibutuhkan library pandas dengan menggunakan method "qcut".

* Sepal Length

In [21]:
# perhitungan atribut sepal length tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut sepal length
binning_interval_sl = pd.qcut(df['sepal_length'],amount_of_binning).value_counts()
print(binning_interval_sl)

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal_length, dtype: int64

In [22]:
# perhitungan atribut sepal length dengan label

binning_label_sl = pd.qcut(df['sepal_length'],amount_of_binning, labels)
l_sepal_binning = binning_label_sl.value_counts()
print(l_sepal_binning)

medium    56
small     52
large     42
Name: sepal_length, dtype: int64

In [23]:
# menampilkan dataframe sepal length
tb_sl = pd.concat((df["sepal_length"],binning_label_sl), axis=1)
tb_sl

    sepal_length sepal_length
0            5.1        small
1            4.9        small
2            4.7        small
3            4.6        small
4            5.0        small
..           ...          ...
145          6.7        large
146          6.3       medium
147          6.5        large
148          6.2       medium
149          5.9       medium

[150 rows x 2 columns]

* Sepal Width

In [24]:
# perhitungan atribut sepal width tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut sepal length
binning_interval_sw = pd.qcut(df['sepal_width'],amount_of_binning).value_counts()
print(binning_interval_sw)

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepal_width, dtype: int64

In [25]:
# perhitungan atribut sepal  width dengan label

binning_label_sw = pd.qcut(df['sepal_width'],amount_of_binning, labels)
w_sepal_binning = binning_label_sw.value_counts()
print(w_sepal_binning)

small     57
medium    51
large     42
Name: sepal_width, dtype: int64

In [26]:
# menampilkan dataframe sepal width
tb_sw = pd.concat((df["sepal_width"],binning_label_sw), axis=1)
tb_sw

    sepal_width sepal_width
0           3.5       large
1           3.0      medium
2           3.2      medium
3           3.1      medium
4           3.6       large
..          ...         ...
145         3.0      medium
146         2.5       small
147         3.0      medium
148         3.4       large
149         3.0      medium

[150 rows x 2 columns]

* Petal Length

In [34]:
# perhitungan atribut petal length tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut sepal length
binning_interval_pl = pd.qcut(df['petal_length'],amount_of_binning).value_counts()
print(binning_interval_pl)

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal_length, dtype: int64

In [28]:
# perhitungan atribut petal length dengan label

binning_label_pl = pd.qcut(df['petal_length'],amount_of_binning, labels)
l_petal_binning = binning_label_pl.value_counts()
print(l_petal_binning)

medium    54
small     50
large     46
Name: petal_length, dtype: int64

In [29]:
# menampilkan dataframe petal length
tb_pl= pd.concat((df["petal_length"],binning_label_pl), axis=1)
tb_pl

    petal_length petal_length
0            1.4        small
1            1.4        small
2            1.3        small
3            1.5        small
4            1.4        small
..           ...          ...
145          5.2        large
146          5.0        large
147          5.2        large
148          5.4        large
149          5.1        large

[150 rows x 2 columns]

* Petal Width

In [35]:
# perhitungan atribut petal width tanpa label

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)
# melakukan binning dengan atribut sepal length
binning_interval_pw = pd.qcut(df['petal_width'],amount_of_binning).value_counts()
print(binning_interval_pw)

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal_width, dtype: int64

In [42]:
# menampilkan dataframe petal width
tb_pw = pd.concat((df["petal_width"],binning_interval_pw), axis=1)
tb_pw

/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py:2955: RuntimeWarning: '<' not supported between instances of 'pandas._libs.interval.Interval' and 'int', sort order is undefined for incomparable objects
  return left.union(right, sort=sort)

                petal_width  petal_width
0                       0.2          NaN
1                       0.2         52.0
2                       0.2         48.0
3                       0.2          NaN
4                       0.2          NaN
...                     ...          ...
148                     2.3          NaN
149                     1.8          NaN
(0.867, 1.6]            NaN         52.0
(0.099, 0.867]          NaN         50.0
(1.6, 2.5]              NaN         48.0

[153 rows x 2 columns]

Menampilkan hasil disktitasi Equal Frequency

In [47]:
pd.concat((binning_interval_sl,binning_interval_sw,binning_interval_pl,binning_interval_pw,df["species"]), axis=1)

,sepal_length,sepal_width,petal_length,petal_width,species
"(0.099, 0.867]",NaN,NaN,NaN,50.0,NaN
"(0.867, 1.6]",NaN,NaN,NaN,52.0,NaN
"(0.999, 2.633]",NaN,NaN,50.0,NaN,NaN
"(1.6, 2.5]",NaN,NaN,NaN,48.0,NaN
"(1.999, 2.9]",NaN,57.0,NaN,NaN,NaN
...,...,...,...,...,...
145,NaN,NaN,NaN,NaN,Iris-virginica
146,NaN,NaN,NaN,NaN,Iris-virginica
147,NaN,NaN,NaN,NaN,Iris-virginica
148,NaN,NaN,NaN,NaN,Iris-virginica
149,NaN,NaN,NaN,NaN,Iris-virginica

###**Soal 2**
**Lakukan proses deskritisasi dengan basis entropy**

**Entropy**

Entropy adalah nilai informasi yang menyatakan ukuran ketidakpastian (impurity) dari attribut dari suatu kumpulan obyek data dalam satuan bit


*   Rumus Entropy:



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

*   Rumus Gain:



$$Gain(E_{new}) = E_{initial} - E_{new}$$
*   Rumus Info:



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$

Membuat sampel yang akan dianalisis/dihitung

In [ ]:
sample = df[["petal_width","sepal_width","sepal_length","petal_length"]]
sample.describe()

       petal_width  sepal_width  sepal_length  petal_length
count   150.000000   150.000000    150.000000    150.000000
mean      1.198667     3.054000      5.843333      3.758667
std       0.763161     0.433594      0.828066      1.764420
min       0.100000     2.000000      4.300000      1.000000
25%       0.300000     2.800000      5.100000      1.600000
50%       1.300000     3.000000      5.800000      4.350000
75%       1.800000     3.300000      6.400000      5.100000
max       2.500000     4.400000      7.900000      6.900000

Membuat kategori random untuk data sampel

In [ ]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2, sample.shape[0]) < 1, "A", "B")
sample

     petal_width  sepal_width  sepal_length  petal_length category
0            0.2          3.5           5.1           1.4        A
1            0.2          3.0           4.9           1.4        B
2            0.2          3.2           4.7           1.3        B
3            0.2          3.1           4.6           1.5        A
4            0.2          3.6           5.0           1.4        B
..           ...          ...           ...           ...      ...
145          2.3          3.0           6.7           5.2        A
146          1.9          2.5           6.3           5.0        B
147          2.0          3.0           6.5           5.2        B
148          2.3          3.4           6.2           5.4        B
149          1.8          3.0           5.9           5.1        B

[150 rows x 5 columns]

Membuat fungsi getOverCategory yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [ ]:
def getOverCategory(col):
  group = sample.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a, b, a+b)

Memasukan fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value:float, col:str)->tuple:
  # get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  # calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  # get value based on category
  less_category_A = less_group.loc["A", col] 
  less_category_B = less_group.loc["B", col] 
  greater_category_A = greater_group.loc["A", col] 
  greater_category_B = greater_group.loc["B", col] 

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Membuat fungsi entropy untuk melakukan perhitungan entropy

In [ ]:
def entropy(d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2]) 
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2]) 
  return np.sum([r1, r2]) * -1

Membuat fungsi info

In [ ]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Membuat fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

In [ ]:
def gain(Einitial, Enew):
  return Einitial - Enew

**1. Petal Width**

In [ ]:
#Membuat Dinitial
a = getOverCategory(("petal_width"))
entropy_a = entropy(a)

print(a)
print(entropy_a)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama : Split 1: 0.1

In [ ]:
split1 = splitter(0.1,"petal_width")
info_split1 = info(split1)
gain(entropy_a, info_split1)

0.01104847098180839

Tes Kedua : Split 2: 1.3

In [ ]:
split2 = splitter(1.3,"petal_width")
info_split2 = info(split2)
gain(entropy_a, info_split2)

0.00021232279799998643

Tes Ketiga : Split 3: 2.4

In [ ]:
split3 = splitter(2.4,"petal_width")
info_split3 = info(split3)
gain(entropy_a, info_split3)

0.0008771143281794958

Jadi pada percobaan split atribut petal width di dapat bahwa split ke 2 dengan nilai 1.3 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.00021232279799998643

**2. Sepal Width**

In [ ]:
#Membuat Dinitial
b = getOverCategory(("sepal_width"))
entropy_b = entropy(b)

print(b)
print(entropy_b)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama : Split 1: 2.2

In [ ]:
split1 = splitter(2.2,"sepal_width")
info_split1 = info(split1)
gain(entropy_b, info_split1)

0.0001729324189373438

Tes Kedua : Split 2: 3.0

In [ ]:
split2 = splitter(3.0,"sepal_width")
info_split2 = info(split2)
gain(entropy_b, info_split2)

0.0009879303562354558

Tes Ketiga : Split 3: 4.0

In [ ]:
split3 = splitter(4.0,"sepal_width")
info_split3 = info(split3)
gain(entropy_b, info_split3)

0.00271470605919788

Jadi dalam percobaan split atribut sepal width di dapati bahwa split ke 1 dengan nilai 2.2 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.0001729324189373438

**3. Petal Length**

In [ ]:
#Membuat Dinitial
c = getOverCategory(("petal_length"))
entropy_c = entropy(c)

print(c)
print(entropy_c)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama : Split 1: 1.2

In [ ]:
split1 = splitter(1.2,"petal_length")
info_split1 = info(split1)
gain(entropy_c, info_split1)

0.003488151753460178

Tes Kedua : Split 2: 4.5

In [ ]:
split2 = splitter(4.5,"petal_length")
info_split2 = info(split2)
gain(entropy_c, info_split2)

0.00010279135197621692

Tes Ketiga : Split 3: 6.6

In [ ]:
split3 = splitter(6.6,"petal_length")
info_split3 = info(split3)
gain(entropy_c, info_split3)

0.0008771143281794958

Jadi dalam percobaan split atribut petal length  bahwa split ke 2 dengan nilai 4.5 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.00010279135197621692

**4. Sepal Length**

In [ ]:
#Membuat Dinitial
d = getOverCategory(("sepal_length"))
entropy_d = entropy(d)

print(d)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama: Split 1: 4.5

In [ ]:
split1 = splitter(4.5,"sepal_length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915

Tes Kedua : Split 2: 5.8

In [ ]:
split2 = splitter(5.8,"sepal_length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.0038893799103313365

Tes Ketiga : Split 3: 7.5

In [ ]:
split3 = splitter(7.5,"sepal_length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0017898381837971877

Jadi pada percobaan split atribut sepal length di dapati bahwa split ke 3 dengan nilai 7.5 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.0017898381837971877