# **Tugas 2**
# **Deskritisasi Data**
Senin, 5 September 2022

 **Carilah data yang bertipe numerik (data klasifikasi)**

# Membaca Data

In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
#untuk membaca dataset
url = "https://raw.githubusercontent.com/RibutDwiArtah023/datamining/gh-pages/IRIS.csv"
dataset = pd.read_csv(url)
pd.options.mode.chained_assignment = None
dataset

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#mengetahui info dari dataset yang telah di baca melalui URL
dataset.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# **Soal 1**
**Lakukan proses diskritisasi dengan equal width dan equal frequency**

**Equal Width Intervals**

Equal width intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

In [ ]:
sepal_length = dataset[["sepal_length"]]
petal_length = dataset[["petal_length"]]
sepal_width = dataset[["sepal_width"]]
petal_width = dataset[["petal_width"]]

membuat fungsi cut yang digunakan untuk mencari interval menggunakan metode Equal Width Intervals

In [ ]:
def cut(col, k):
  intervals = pd.cut(data[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

In [ ]:
def toCategory(list_interval, col):
  # get length interval
  length = len(list_interval)

  # sorting interval
  sort_interval = np.sort(list_interval, axis=0)

  # get category from interval
  categories = np.array([chr(65+i) for i in range(length)])[:, None]

  # Combine into interval data
  intervals = np.hstack((sort_interval, categories))

  # operate all data
  newCol = []
  for i, row in data.iterrows():
    d = row[col]
    for interval in intervals:
      if d >= interval[0].astype(float) and d <= interval[1].astype(float):
        newCol.append(interval[2])
        break

  # return new column category
  return np.array(newCol, dtype=str)

mencari interval dengan membaginya menjadi 3 bagian

In [ ]:
interval_sepal_length = cut("sepal.length", 3)
interval_petal_length = cut("petal.length", 3)
interval_sepal_width = cut("sepal.width", 3)
interval_petal_width = cut("petal.width", 3)

print("interval sepal.length = ", interval_sepal_length)
print("interval petal.length = ", interval_petal_length)
print("interval sepal.width = ", interval_sepal_width)
print("interval petal.width = ", interval_petal_width)

interval sepal.length =  [[5.5, 6.7], [4.296, 5.5], [6.7, 7.9]]
interval petal.length =  [[2.967, 4.933], [0.994, 2.967], [4.933, 6.9]]
interval sepal.width =  [[2.8, 3.6], [1.998, 2.8], [3.6, 4.4]]
interval petal.width =  [[0.9, 1.7], [0.0976, 0.9], [1.7, 2.5]]

Menampilkan hasil dari pembagian category

In [ ]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(petal_length)
display(sepal_width)
display(petal_width)

**Equal Frequency Intervals** <br>
Equal-frequency intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

In [ ]:
sepal_length = data[["sepal.length"]]
petal_length = data[["petal.length"]]
sepal_width = data[["sepal.width"]]
petal_width = data[["petal.width"]]

Pandas menyediakan method qcut untuk mencari nilai interval dari Equal_Frequency Intervals

In [ ]:
def qcut(col, k):
  intervals = pd.qcut(data[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

mencari interval dengan membaginya menjadi 3 bagian

In [ ]:
interval_sepal_length = qcut("sepal.length", 3)
interval_petal_length = qcut("petal.length", 3)
interval_sepal_width = qcut("sepal.width", 3)
interval_petal_width = qcut("petal.width", 3)

print("interval sepal.length = ", interval_sepal_length)
print("interval petal.length = ", interval_petal_length)
print("interval sepal.width = ", interval_sepal_width)
print("interval petal.width = ", interval_petal_width)

interval sepal.length =  [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
interval petal.length =  [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
interval sepal.width =  [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
interval petal.width =  [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

Menampilkan hasil pembagian category

In [ ]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(petal_length)
display(sepal_width)
display(petal_width)

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        C
146           6.3        B
147           6.5        C
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     sepal.width category
0            3.5        C
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        C
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        C
149          3.0        B

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

# **Soal 2**
**Lakukan proses deskritisasi dengan basis entropy**

**Entropy**

Entropy adalah nilai informasi yang menyatakan ukuran ketidakpastian(impurity) dari attribut dari suatu kumpulan obyek data dalam satuan bit

membuat sampel untuk dianalisis

In [ ]:
sample = data[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

membuat category random untuk semua data

In [ ]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2, sample.shape[0]) < 1, "A", "B")
sample

     sepal.length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

membuat fungsi getOverCategory yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [ ]:
def getOverCategory(col):
  group = sample.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a, b, a+b)

fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value:float, col:str)->tuple:
  # get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  # calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  # get value based on category
  less_category_A = less_group.loc["A", col] 
  less_category_B = less_group.loc["B", col] 
  greater_category_A = greater_group.loc["A", col] 
  greater_category_B = greater_group.loc["B", col] 

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Membuat fungsi entropy untuk mencari nilai entropy

Rumus Entropy :

$$Entropy (D_{1}) = - \sum_{i=1}^{m} pi \log_{2} pi$$

In [ ]:
def entropy(d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2]) 
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2]) 
  return np.sum([r1, r2]) * -1

Membuat fungsi info

In [ ]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Membuat fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru.

Rumus Mencari Gain :

$$Gain(E_{new}) = (E_{initial}) - (E_{new})$$

In [ ]:
def gain(Einitial, Enew):
  return Einitial - Enew

Membuat DInitial

In [ ]:
D = getOverCategory("sepal.length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama : Split 1:4.4

In [ ]:
split1  = splitter(4.4, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

Tes Kedua : Split 2:5.5

In [ ]:
split2  = splitter(5.5, "sepal.length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

Tes Ketiga : Split 3:7.0

In [ ]:
split3  = splitter(7.0, "sepal.length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658

Dari seluruh hasil percobaan tes split yang telah dilakukan, maka diperoleh hasil split terbaik adalah split 3 yang mwemberikan keuntungan informasi sebesar 0.0005490214732508658, karena hasil tes split 3 memiliki nilai split yang terendah.